<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>OutSystems.ExternalLibraries.RuntimeContext</RootNamespace>
    <AssemblyName>OutSystems.ExternalLibraries.RuntimeContext</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="OutSystems.ExternalLibraries.SDK" Version="1.5.0" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Resources\app_icon.png" />
    <EmbeddedResource Include="Resources\action_icon.png" />
  </ItemGroup>

</Project>
